### PR TITLE
redux fix

### PR DESCRIPTION
**Pull request by tijs**
state is there now. stay away form the fancy middleware until basics work ;)

### CODE REVIEW

**Comment by tijs** [comment]
@robertgaal looks like your having fun. keep it up 💯

**Comment by robertgaal** [comment]
Thanks Tijs! I was actually served an error by React saying I needed to add this code:

https://github.com/reactjs/react-redux/releases/tag/v2.0.0

But with your version, it seems no longer necessary? Is that due to the logger you added? I owe you one man! Super helpful!

**Comment by tijs** [comment]
The logger is just a useful tool you should use to make your life easier. The problem was that you used anonymous functions in combinereducer. You can just pass an object  of reducers to that function.

I did not try to get the hot reloading to work though

**Comment by robertgaal** [comment]
Aaah got it. Thanks for the help!

**Pull request merged**
